USE_INIT=False                               #使用当前配置请设为True,否则将尝试从外部获取参数
PLEX_TOKEN="xNjbvCpt-P1898dyDACz"            #Plextoken获取,具体方法请自行查找 "zZzxxxxxxxJssiw2zcy" *必须设置
PLEX_URL="http://plex.beimou.net:32400"         #Plexurl "http://plex.xxx.cn:32400" *必须设置
RECOVER=False                               #是否覆盖已有的拼音推送订阅
LIB_NAME=''                                 #要推送订阅的库名(存在时库编号不生效)
LIB_NUMBER=0                                #要推送订阅的库编号(不使用库编号则设为0)
ENABLE_LOG=1                                #是否输出进度条
MEDIA_ID=0
MR_AN="eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTY2MzU1MzU3NiwianRpIjoiMmM2ZGY1YTEtMzMyMy00NWRhLWJjZmUtODY3MmI2YTJjOGE5IiwidHlwZSI6ImFjY2VzcyIsInN1YiI6MSwibmJmIjoxNjYzNTUzNTc2LCJleHAiOjE2NjYxNDU1NzZ9.THM-98Z1AZWdu_xyOeRBe7RzMc4gUUJhQv-BtBFcW7c"
MR_URL="http://mr.0bm.cn:60"                #最后不要加斜杠